package com.example.project.models;

public enum RequestEnum {
    REGISTER_USER,
    LOGIN_USER,
    GO_TO_SCORE_BOARD,
    GO_TO_PROFILE_MENU,
    GO_TO_GLOBAL_CHAT,
    UPDATE_SCOREBOARD_DATA,
    BACK,
    EDIT_MESSAGE,
    UPDATE_PUBLIC_CHAT,
    SEND_PUBLIC_MESSAGE,
    DELETE_FOR_EVERYONE,
    DELETE_FOR_ME,
    UPDATE_LOGGED_IN_USER_CHATS,
    GET_SUGGESTION_PRIVATE_CHATS,
    CREATE_PRIVATE_CHAT,
    GO_TO_A_PRIVATE_CHAT,
    SEND_MESSAGE;
}
