package com.example.project.models;

public enum RequestEnum {
    REGISTER_USER,
    LOGIN_USER,
    GO_TO_SCORE_BOARD,
    GO_TO_PROFILE_MENU,
    GO_TO_GLOBAL_CHAT,
    GO_TO_PLAY_GAME_SETTINGS,
    UPDATE_SCOREBOARD_DATA,
    BACK,
    CHANGE_NICKNAME,
    CHANGE_PASSWORD,
    CHANGE_PROFILE_PICTURE,
    CLEAR_PLAYERS_IN_GAME,
    UPDATE_SEARCHED_PLAYERS,
    UPDATE_IN_GAME_PLAYERS,
    ADD_PLAYER,
    SET_NUMBER_OF_PLAYERS,
    ;
}
